<a href="https://colab.research.google.com/github/itsayushiii/K-Fold-Cross-Validation/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size = 0.2, random_state = 21)

In [6]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test , y_test)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

In [7]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9861111111111112

In [16]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.5083333333333333

In [28]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [29]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [30]:
def get_score(model, x_train ,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [31]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

0.4986072423398329

In [32]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [33]:
scores_l = []
scores_svm =[]
scores_rf = []

for tain_index, test_index in kf.split(digits.data):
  x_train,x_test,y_train, y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index], digits.target[test_index]

  scores_l.append(get_score(LogisticRegression(), x_train,x_test,y_train ,y_test))
  scores_svm.append(get_score(SVC(),x_train,x_test,y_train ,y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators =40), x_train,x_test,y_train ,y_test))

In [34]:
scores_l

[0.3672787979966611, 0.34223706176961605, 0.35225375626043404]

In [35]:
scores_svm

[0.39065108514190316, 0.35392320534223703, 0.3639398998330551]

In [36]:
scores_rf

[0.3121869782971619, 0.2337228714524207, 0.332220367278798]

implementing above code using sklearn


In [37]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data , digits.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [38]:
cross_val_score(SVC(),digits.data , digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [39]:
cross_val_score(RandomForestClassifier(),digits.data , digits.target)

array([0.92777778, 0.90277778, 0.95821727, 0.96935933, 0.93036212])